import { readFile, writeFile } from "node:fs/promises";
import { closeDatabase, openDatabase } from "../dist/packages/audit/store.js";
import { approveDraft, auditForCovenant, createDraft } from "../dist/packages/domain/lifecycle.js";
import { buildExport, toJson, toMarkdown } from "../dist/packages/export/serializers.js";

const db = openDatabase(".data/verification.sqlite");
try {
  const draft = createDraft(db, {
    name: "Verification Covenant",
    purpose: "Prove the foundation export contract.",
    coveredExposure: "Local test exposure",
    objective: "Preserve a durable policy record.",
    timeHorizon: "10 years",
    maximumIntendedConcentration: 0.35,
    maximumTolerableDrawdown: 0.25,
    reviewRules: ["Review when the threshold is reached"],
    candidateActions: ["Review the policy"],
    falsifiers: [],
    deescalationConditions: [],
    reentryConditions: [],
    cooldownPolicy: "Fourteen days",
    notes: "Generated by verify:core.",
  });
  const covenant = approveDraft(db, draft.id);
  const exported = buildExport(covenant, auditForCovenant(db, covenant.id));
  const jsonPath = ".data/verification-export.json";
  const markdownPath = ".data/verification-export.md";
  await writeFile(jsonPath, toJson(exported));
  await writeFile(markdownPath, toMarkdown(exported));
  const [json, markdown] = await Promise.all([readFile(jsonPath, "utf8"), readFile(markdownPath, "utf8")]);
  for (const [label, text] of [["JSON", json], ["Markdown", markdown]]) {
    for (const required of ["version", "approved", "audit"]) {
      if (!text.toLowerCase().includes(required)) throw new Error(`${label} export is missing ${required}`);
    }
  }
  console.log(`exports verified: ${jsonPath}, ${markdownPath}`);
} finally {
  closeDatabase(db);
}
